version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: auth-postgres
    restart: always
    environment:
      POSTGRES_DB: urbanradar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: urban
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
